---
galaxy_info:
  role_name: opnsense_dhcp
  author: Chris Deever
  description: Configure OPNsense Kea DHCP static reservations via API
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: OPNsense
      versions:
        - all

dependencies: []
