---
galaxy_info:
  role_name: opnsense_dns
  author: Chris Deever
  description: Configure OPNsense Unbound DNS host overrides
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: OPNsense
      versions:
        - all

dependencies: []
