---
# Configure VyOS NAT masquerade

- name: Configure source NAT masquerade
  vyos.vyos.vyos_config:
    lines:
      - set nat source rule 100 outbound-interface name '{{ firewall_nat_outbound_interface }}'
      - set nat source rule 100 source address '0.0.0.0/0'
      - set nat source rule 100 translation address masquerade
    save: true
  notify: save vyos config
