---
# Handlers for opnsense_dhcp role (Kea DHCP)

- name: reconfigure dhcp
  ansible.builtin.uri:
    url: "{{ opnsense_api_url }}/kea/service/reconfigure"
    method: POST
    user: "{{ opnsense_api_key }}"
    password: "{{ opnsense_api_secret }}"
    force_basic_auth: true
    validate_certs: "{{ opnsense_validate_certs }}"
  delegate_to: localhost
